<Project>
  <PropertyGroup>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)..\..\..\.godot\tool-output\dotnet-probes\$(MSBuildProjectName)\obj\</BaseIntermediateOutputPath>
    <BaseOutputPath>$(MSBuildThisFileDirectory)..\..\..\.godot\tool-output\dotnet-probes\$(MSBuildProjectName)\bin\</BaseOutputPath>
  </PropertyGroup>
</Project>
